name: Build and Deploy to monsterasp.net

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore StudentData/StudentData.csproj

      - name: Publish
        run: dotnet publish StudentData/StudentData.csproj -c Release -o ./publish

      - name: Deploy to monsterasp.net (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.	site60482.siteasp.net }}
          username: ${{ secrets.site60482 }}
          password: ${{ secrets.2w=D@7Zyg#4A }}
          local-dir: ./publish/
          server-dir: ${{ secrets.\wwwroot }}
          protocol: ftps
